version: 2
jobs:
   test:
     docker:
       - image: circleci/ruby:2.3.4
     steps:
       - checkout
       - run:
          name: Install Dawnscanner
          command: 'gem install dawnscanner'
       - store_test_results:
          path: test-reports/
       - run:
          name: Run Dawnscanner
          command: '"dawn railsgoat/" > test-reports/scan_results.txt'
workflows:
 version: 2
 build_and_test:
  jobs:
    - test 