version: 2
jobs:
  test:
    pre:
      docker:
        - image: circleci/ruby:2.3.4
      steps:
        - checkout
        - run:
            name: Install Dawnscanner
            command: 'gem install dawnscanner'
workflows:
  version: 2
  build_and_test:
  jobs:
    - test 