version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.3.4
     steps:
       - checkout
       - run:
          name: Get PWD
          command: 'pwd'
       - run:
          name: List Files
          command: 'ls -l'
       - run:
          name: Install Dawnscanner
          command: 'gem install dawnscanner'
   test:
     - run:
        name: Run Dawnscanner
        command: 'dawn railsgoat/'
     - run:
        name: Create artifact directory
        command: 'sudo mkdir $CIRCLE_ARTIFACTS/scan_result'
     - run:
        name: Copy scan result to artifact directory
          command: 'sudo mv /home/circleci/dawnscanner/results/railsgoat/*/summary.txt $CIRCLE_ARTIFACTS/scan_result'