version: 2
jobs:
   build:
     docker:
       - image: circleci/ruby:2.3.4
     steps:
       - run:
          name: Get PWD
          command:  'pwd'
       - run:
          name: Install Dawnscanner
          command: 'gem install dawnscanner'
       - run:
          name: Run Dawnscanner
          command: 'dawn railsgoat/'
test:
  post:
    - mkdir $CIRCLE_ARTIFACTS/scan_output
    - mv home/circleci/dawnscanner/results/railsgoat/*/summary.txt created $CIRCLE_ARTIFACTS/scan_output
