version: 2
jobs:
   test:
     docker:
       - image: circleci/ruby:2.3.4
     steps:
       - checkout
       - run:
          name: Install Dawnscanner
          command: 'gem install dawnscanner'
       - run:
          name: Run Dawnscanner
          command: '"dawn railsgoat/" > test-results/scan_results.txt'
       - run:
          name: View results
          command: 'sudo ls -l /home/circleci/project/'
workflows:
 version: 2
 build_and_test:
  jobs:
    - test 