version: 2
jobs:
   test:
     pre:
       docker:
         - image: circleci/ruby:2.3.4
     post:
       - case $CIRCLE_NODE_INDEX in 0) ./script/dawnscanner ;; esac:
           parallel: true
workflows:
 version: 2
 build_and_test:
  jobs:
    - test 