version: 2
jobs:
  test:
    pre:
      docker:
        - image: circleci/ruby:2.3.4
      steps:
        - checkout
        - run:
            name: Install Dawnscanner
            command: 'gem install dawnscanner'
        - store_test_results:
            path: test-reports/
        - run:
            name: Run Dawnscanner
            command: 'dawn railsgoat/'
    post:
      - sudo cat /home/circleci/dawnscanner/results/railsgoat/20180203/third_party_vulnerabilities.txt  
workflows:
  version: 2
  build_and_test:
  jobs:
    - test 