version: 2
jobs:
   test:
     docker:
       - image: circleci/ruby:2.3.4
     steps:
       - checkout
       - run:
          name: Install Dawnscanner
          command: 'gem install dawnscanner'
       - run:
          name: Run Dawnscanner
          command: 'dawn railsgoat/ -F test-reports/dawnscanner_results.txt'
       - store_artifacts:
          path: test-reports/
          destination: tr1
       - store_test_results:
          path: test-reports/
workflows:
 version: 2
 build_and_test:
  jobs:
    - test 