version: 2
jobs:
   build:
     working-directory: ~/circlecitest
     docker:
       - image: circleci/ruby:2.3.4
     environment:
          CIRCLE_ARTIFACTS: /home/circleci
     steps:
       - checkout
       - run:
            name: Get PWD
            command:  'ls -l'
       - run:
            name: Check CIRCLE_ARTIFACTS
            command: echo $CIRCLE_ARTIFACTS
       - run:
            name: Install Dawnscanner certificate
            command: 'gem cert --add <(curl -Ls https://raw.githubusercontent.com/thesp0nge/dawnscanner/master/certs/paolo_at_dawnscanner_dot_org.pem)'
       - run:
            name: Install Dawnscanner
            command: 'gem install dawnscanner'
       - run:
            name: Run Dawnscanner
            command: 'dawn railsgoat/'
